import type { ChatMessage, Group, Member, Notif, Post, Thread } from "./types";

export const YOU_ID = "you";

const h = (n: number) => Date.now() - n * 60 * 60 * 1000;
const d = (n: number) => Date.now() - n * 24 * 60 * 60 * 1000;

export const INTERESTS = [
  "gardening",
  "mutual-aid",
  "bikes",
  "cooking",
  "hiking",
  "art",
  "language",
  "parenting",
  "making",
  "music",
  "wellness",
  "organizing",
] as const;

export const SKILL_POOL = [
  "woodworking",
  "bike repair",
  "Spanish",
  "composting",
  "fermentation",
  "childcare",
  "graphic design",
  "yoga",
  "electrical",
  "carpentry",
  "tutoring",
  "cooking",
  "mural painting",
  "guitar",
  "software",
  "3D printing",
  "herbalism",
  "photography",
  "baking",
  "Arabic",
  "community organizing",
  "surfing",
  "zero waste",
  "piano",
  "Russian",
  "auto repair",
  "welding",
  "textiles",
  "grant writing",
  "gardening",
];

export const members: Member[] = [
  {
    id: YOU_ID,
    name: "Alex Rivera",
    handle: "alex",
    neighborhood: "Echo Park",
    bio: "Making space for neighbors to trade skills, tools, and time. Always down to build something useful.",
    skills: ["woodworking", "Spanish", "composting"],
    interests: ["gardening", "mutual-aid", "making"],
    groupIds: ["la-commons", "echo-park-aid", "eastside-growers", "language-circle"],
    tone: "sage",
    initials: "AR",
  },
  {
    id: "maya",
    name: "Maya Chen",
    handle: "maya",
    neighborhood: "Silver Lake",
    bio: "Ferments everything. Designs the flyers. Keeps the starter library alive.",
    skills: ["fermentation", "graphic design", "yoga"],
    interests: ["cooking", "wellness", "art"],
    groupIds: ["la-commons", "culinary-commons", "eastside-growers"],
    tone: "teal",
    initials: "MC",
  },
  {
    id: "jordan",
    name: "Jordan Hale",
    handle: "jordan",
    neighborhood: "Highland Park",
    bio: "If it has wheels or wires, I can probably fix it. Teaching Saturday shop hours.",
    skills: ["bike repair", "electrical", "carpentry"],
    interests: ["bikes", "making", "mutual-aid"],
    groupIds: ["la-commons", "bike-kitchen", "skill-share"],
    tone: "forest",
    initials: "JH",
  },
  {
    id: "priya",
    name: "Priya Shah",
    handle: "priya",
    neighborhood: "Pasadena",
    bio: "Parent, tutor, and the person who always brings extra snacks.",
    skills: ["childcare", "tutoring", "cooking"],
    interests: ["parenting", "cooking", "mutual-aid"],
    groupIds: ["la-commons", "skill-share", "culinary-commons"],
    tone: "sand",
    initials: "PS",
  },
  {
    id: "diego",
    name: "Diego Morales",
    handle: "diego",
    neighborhood: "Boyle Heights",
    bio: "Walls, alleys, and community spaces. Paint is a public language.",
    skills: ["mural painting", "guitar", "Spanish"],
    interests: ["art", "music", "organizing"],
    groupIds: ["la-commons", "dtla-makers", "echo-park-aid"],
    tone: "sky",
    initials: "DM",
  },
  {
    id: "sam",
    name: "Sam Okonkwo",
    handle: "sam",
    neighborhood: "Culver City",
    bio: "Prints parts for people who are building the real thing.",
    skills: ["software", "3D printing", "tutoring"],
    interests: ["making", "organizing", "bikes"],
    groupIds: ["la-commons", "dtla-makers", "skill-share"],
    tone: "stone",
    initials: "SO",
  },
  {
    id: "leah",
    name: "Leah Kim",
    handle: "leah",
    neighborhood: "Los Feliz",
    bio: "Trails before inbox. Herbs on the fire escape. Camera always in the pack.",
    skills: ["herbalism", "photography", "gardening"],
    interests: ["hiking", "wellness", "gardening"],
    groupIds: ["la-commons", "trail-club", "eastside-growers"],
    tone: "sage",
    initials: "LK",
  },
  {
    id: "omar",
    name: "Omar Haddad",
    handle: "omar",
    neighborhood: "Downtown",
    bio: "Sourdough at dawn, meetings at dusk. Building little infrastructures of care.",
    skills: ["baking", "Arabic", "community organizing"],
    interests: ["organizing", "cooking", "mutual-aid"],
    groupIds: ["la-commons", "echo-park-aid", "culinary-commons"],
    tone: "sand",
    initials: "OH",
  },
  {
    id: "wren",
    name: "Wren Solis",
    handle: "wren",
    neighborhood: "Venice",
    bio: "Tide charts, trash bags, and a stubborn belief in public shoreline.",
    skills: ["surfing", "zero waste", "community organizing"],
    interests: ["wellness", "organizing", "hiking"],
    groupIds: ["la-commons", "trail-club", "echo-park-aid"],
    tone: "sky",
    initials: "WS",
  },
  {
    id: "nina",
    name: "Nina Petrov",
    handle: "nina",
    neighborhood: "Echo Park",
    bio: "Lessons after work, tomatoes on the porch, Russian poetry on request.",
    skills: ["piano", "Russian", "gardening"],
    interests: ["music", "language", "gardening"],
    groupIds: ["la-commons", "eastside-growers", "language-circle"],
    tone: "teal",
    initials: "NP",
  },
  {
    id: "chris",
    name: "Chris Alvarez",
    handle: "chris",
    neighborhood: "Atwater Village",
    bio: "Shop nights for anyone who wants to stop being afraid of engines.",
    skills: ["auto repair", "welding", "mentoring"],
    interests: ["making", "mutual-aid", "bikes"],
    groupIds: ["la-commons", "skill-share", "bike-kitchen"],
    tone: "forest",
    initials: "CA",
  },
  {
    id: "fatima",
    name: "Fatima Diallo",
    handle: "fatima",
    neighborhood: "Leimert Park",
    bio: "Turns community work into funded work. Dance as the other organizing tool.",
    skills: ["textiles", "grant writing", "community organizing"],
    interests: ["art", "organizing", "music"],
    groupIds: ["la-commons", "dtla-makers", "skill-share"],
    tone: "stone",
    initials: "FD",
  },
];

export const groups: Group[] = [
  {
    id: "la-commons",
    name: "Los Angeles Commons",
    purpose: "The citywide network for neighborhood groups sharing skills, surplus, and care.",
    neighborhood: "Los Angeles",
    memberIds: members.map((m) => m.id),
    topics: ["mutual-aid", "organizing", "making"],
    openness: "open",
    tone: "forest",
    mapX: 54,
    mapY: 48,
  },
  {
    id: "echo-park-aid",
    name: "Echo Park Mutual Aid",
    purpose: "Tools, meals, rides, and neighbor-to-neighbor help in Echo Park and Elysian.",
    neighborhood: "Echo Park",
    memberIds: ["you", "diego", "omar", "nina", "wren"],
    topics: ["mutual-aid", "parenting", "cooking"],
    openness: "open",
    parentId: "la-commons",
    tone: "sage",
    mapX: 48,
    mapY: 42,
  },
  {
    id: "eastside-growers",
    name: "Eastside Growers",
    purpose: "Backyard harvests, compost drops, seed swaps, and slow food in the hills.",
    neighborhood: "Silver Lake",
    memberIds: ["you", "maya", "leah", "nina"],
    topics: ["gardening", "cooking", "wellness"],
    openness: "open",
    parentId: "la-commons",
    tone: "teal",
    mapX: 52,
    mapY: 38,
  },
  {
    id: "bike-kitchen",
    name: "Bike Kitchen Eastside",
    purpose: "Open shop, spare parts, and rides that leave no one stranded.",
    neighborhood: "Boyle Heights",
    memberIds: ["jordan", "chris", "sam"],
    topics: ["bikes", "making", "mutual-aid"],
    openness: "open",
    parentId: "la-commons",
    tone: "sky",
    mapX: 62,
    mapY: 52,
  },
  {
    id: "skill-share",
    name: "LA Skill Share",
    purpose: "Trade what you know for what you need. No invoices, just reciprocity.",
    neighborhood: "Citywide",
    memberIds: ["jordan", "priya", "sam", "chris", "fatima"],
    topics: ["making", "parenting", "language"],
    openness: "open",
    parentId: "la-commons",
    tone: "sand",
    mapX: 44,
    mapY: 56,
  },
  {
    id: "trail-club",
    name: "Angeles Trail Club",
    purpose: "Dawn hikes, trail care, and a group text that actually gets people outside.",
    neighborhood: "Griffith Park",
    memberIds: ["leah", "wren", "maya"],
    topics: ["hiking", "wellness"],
    openness: "open",
    parentId: "la-commons",
    tone: "forest",
    mapX: 58,
    mapY: 28,
  },
  {
    id: "language-circle",
    name: "Language Circle",
    purpose: "Conversation hours in Spanish, Arabic, Russian, Korean, and whatever you bring.",
    neighborhood: "Los Feliz",
    memberIds: ["nina", "diego", "omar", "you"],
    topics: ["language"],
    openness: "open",
    parentId: "la-commons",
    tone: "teal",
    mapX: 50,
    mapY: 34,
  },
  {
    id: "dtla-makers",
    name: "DTLA Makers",
    purpose: "Shared benches, printers, and projects that outgrow a kitchen table.",
    neighborhood: "Downtown",
    memberIds: ["diego", "sam", "fatima"],
    topics: ["making", "art"],
    openness: "protected",
    parentId: "la-commons",
    tone: "stone",
    mapX: 56,
    mapY: 58,
  },
  {
    id: "culinary-commons",
    name: "Culinary Commons",
    purpose: "Surplus produce, bulk buys, and the kind of dinners that turn into organizing.",
    neighborhood: "Citywide",
    memberIds: ["maya", "priya", "omar"],
    topics: ["cooking", "gardening", "mutual-aid"],
    openness: "open",
    parentId: "la-commons",
    tone: "sand",
    mapX: 40,
    mapY: 62,
  },
];

export const posts: Post[] = [
  {
    id: "p1",
    type: "request",
    title: "Circular saw for a weekend bookshelf build",
    body: "Building three low shelves for the Echo Park little free pantry. Need a circular saw Saturday morning through Sunday. Happy to return it sharpened, plus extra sourdough.",
    authorId: "omar",
    groupId: "echo-park-aid",
    topics: ["making", "mutual-aid"],
    location: "Echo Park",
    createdAt: h(2),
    helpers: [],
    rsvps: [],
    completed: false,
    comments: [
      {
        id: "c1",
        authorId: "jordan",
        body: "I have a Dewalt you can borrow if no one closer replies. I can drop it Friday night.",
        createdAt: h(1.2),
      },
    ],
    mapX: 47,
    mapY: 44,
    savedBy: [],
  },
  {
    id: "p2",
    type: "offer",
    title: "Kombucha SCOBYs — take as many as you want",
    body: "The hotel is overflowing. Continuous brew jars, tea, and a 10-minute demo included. Bring a glass jar.",
    authorId: "maya",
    groupId: "eastside-growers",
    topics: ["cooking", "gardening"],
    location: "Silver Lake",
    createdAt: h(5),
    helpers: ["nina"],
    rsvps: [],
    completed: false,
    comments: [
      {
        id: "c2",
        authorId: "nina",
        body: "Coming by after 6 with two mason jars.",
        createdAt: h(4),
      },
    ],
    mapX: 51,
    mapY: 37,
    savedBy: [YOU_ID],
  },
  {
    id: "p3",
    type: "event",
    title: "Temescal Canyon ridge hike",
    body: "Easy-moderate, 4 miles. Meet at the lower lot. Water, a snack, and shoes with grip. We go slow on purpose.",
    authorId: "leah",
    groupId: "trail-club",
    topics: ["hiking", "wellness"],
    location: "Pacific Palisades",
    createdAt: h(8),
    helpers: [],
    rsvps: ["wren", "maya", YOU_ID],
    eventAt: Date.now() + 36 * 60 * 60 * 1000,
    completed: false,
    comments: [],
    mapX: 18,
    mapY: 48,
    savedBy: [],
  },
  {
    id: "p4",
    type: "discussion",
    title: "How do we start a little free pantry that actually stays stocked?",
    body: "The box is up. Filling it is the harder part. What cadences have worked in your neighborhood — a weekly bulk buy, a signal chat, a rotating steward?",
    authorId: "omar",
    groupId: "echo-park-aid",
    topics: ["mutual-aid", "organizing"],
    location: "Echo Park",
    createdAt: d(1),
    helpers: [],
    rsvps: [],
    completed: false,
    comments: [
      {
        id: "c3",
        authorId: "fatima",
        body: "A two-person steward pair plus a Sunday restock from Culinary Commons worked in Leimert. I can share the simple roster.",
        createdAt: h(20),
      },
    ],
    mapX: 46,
    mapY: 41,
    savedBy: [],
  },
  {
    id: "p5",
    type: "request",
    title: "Last-minute childcare Thursday 3–6pm",
    body: "Parent-teacher conference ran long. Looking for someone kind with kids for three hours in Pasadena. Can pay, trade tutoring, or both.",
    authorId: "priya",
    groupId: "skill-share",
    topics: ["parenting", "mutual-aid"],
    location: "Pasadena",
    createdAt: h(3),
    helpers: [],
    rsvps: [],
    completed: false,
    comments: [],
    mapX: 78,
    mapY: 22,
    savedBy: [],
  },
  {
    id: "p6",
    type: "offer",
    title: "Free 3D prints for community projects this month",
    body: "Printer time is open for brackets, replacement knobs, classroom widgets, and bike bits. Send a file or a sketch.",
    authorId: "sam",
    groupId: "dtla-makers",
    topics: ["making", "bikes"],
    location: "Culver City",
    createdAt: d(2),
    helpers: ["jordan"],
    rsvps: [],
    completed: false,
    comments: [],
    mapX: 28,
    mapY: 64,
    savedBy: [],
  },
  {
    id: "p7",
    type: "resource",
    title: "Mural permission checklist for LA alleys",
    body: "A one-pager: who to call, how to get the adjacent owner on board, and what the city actually cares about. Used it on 4th Street last spring.",
    authorId: "diego",
    groupId: "dtla-makers",
    topics: ["art", "organizing"],
    location: "Boyle Heights",
    createdAt: d(3),
    helpers: [],
    rsvps: [],
    completed: false,
    comments: [],
    mapX: 64,
    mapY: 54,
    savedBy: [YOU_ID],
  },
  {
    id: "p8",
    type: "project",
    title: "Venice shoreline cleanup — ongoing",
    body: "Every other Saturday, 8am at the paddle tennis courts. Gloves and bags provided. We log what we pull so the city cannot shrug.",
    authorId: "wren",
    groupId: "trail-club",
    topics: ["organizing", "wellness"],
    location: "Venice",
    createdAt: d(4),
    helpers: ["leah"],
    rsvps: ["leah", YOU_ID],
    completed: false,
    comments: [],
    mapX: 14,
    mapY: 70,
    savedBy: [],
  },
  {
    id: "p9",
    type: "offer",
    title: "Beginner piano in exchange for garden help",
    body: "Thirty minutes on the upright after 5pm. I need someone who actually likes weeding and can tell a tomato from a volunteer tomatillo.",
    authorId: "nina",
    groupId: "eastside-growers",
    topics: ["music", "gardening"],
    location: "Echo Park",
    createdAt: h(14),
    helpers: [],
    rsvps: [],
    completed: false,
    comments: [],
    mapX: 49,
    mapY: 43,
    savedBy: [],
  },
  {
    id: "p10",
    type: "offer",
    title: "Engine diagnosis for the cost of parts",
    body: "Bring it to the Atwater alley shop Thursday evenings. I will tell you the truth and show you the bolt. No upsell.",
    authorId: "chris",
    groupId: "skill-share",
    topics: ["making", "mutual-aid"],
    location: "Atwater Village",
    createdAt: d(1.5),
    helpers: [],
    rsvps: [],
    completed: false,
    comments: [
      {
        id: "c4",
        authorId: "jordan",
        body: "Can I send a neighbor whose Civic has been limping? They are cash-tight this month.",
        createdAt: h(18),
      },
    ],
    mapX: 55,
    mapY: 36,
    savedBy: [],
  },
  {
    id: "p11",
    type: "discussion",
    title: "Grant writing circle — let's apply together",
    body: "Three of us, two hours, one shared doc. If your group has a project and no staff grant writer, pull up a chair.",
    authorId: "fatima",
    groupId: "skill-share",
    topics: ["organizing", "art"],
    location: "Leimert Park",
    createdAt: h(26),
    helpers: [],
    rsvps: [],
    completed: false,
    comments: [],
    mapX: 42,
    mapY: 72,
    savedBy: [],
  },
  {
    id: "p12",
    type: "event",
    title: "Saturday open shop — Bike Kitchen",
    body: "Stands, tools, and a parts bin. Learn a repair or leave with a rideable bike. Kids welcome with a grown-up.",
    authorId: "jordan",
    groupId: "bike-kitchen",
    topics: ["bikes", "making"],
    location: "Boyle Heights",
    createdAt: h(10),
    helpers: [],
    rsvps: ["chris", "sam"],
    eventAt: Date.now() + 3 * 24 * 60 * 60 * 1000,
    completed: false,
    comments: [],
    mapX: 63,
    mapY: 53,
    savedBy: [],
  },
  {
    id: "p13",
    type: "request",
    title: "Spanish conversation partner, weekday mornings",
    body: "I am B1 and stuck. Coffee or a walk around the lake, 45 minutes, twice a week. I can trade woodworking or compost help.",
    authorId: YOU_ID,
    groupId: "language-circle",
    topics: ["language"],
    location: "Echo Park",
    createdAt: h(30),
    helpers: ["diego"],
    rsvps: [],
    completed: false,
    comments: [
      {
        id: "c5",
        authorId: "diego",
        body: "Lake walk Tuesday? I need the steps anyway.",
        createdAt: h(22),
      },
    ],
    mapX: 48,
    mapY: 40,
    savedBy: [],
  },
  {
    id: "p14",
    type: "resource",
    title: "Bulk buy list — grains, beans, oil",
    body: "Shared wholesale sheet for Culinary Commons. Add what your household can store. Pickup is Sunday at Omar's.",
    authorId: "omar",
    groupId: "culinary-commons",
    topics: ["cooking", "mutual-aid"],
    location: "Downtown",
    createdAt: d(5),
    helpers: [],
    rsvps: [],
    completed: false,
    comments: [],
    mapX: 57,
    mapY: 57,
    savedBy: [],
  },
];

export const threads: Thread[] = [
  { id: "t1", participantIds: [YOU_ID, "maya"] },
  { id: "t2", participantIds: [YOU_ID, "jordan"] },
  { id: "t3", participantIds: [YOU_ID, "diego"] },
];

export const messages: ChatMessage[] = [
  {
    id: "m1",
    threadId: "t1",
    authorId: "maya",
    body: "The SCOBYs are happiest if you pick up after 5 — the porch gets shade then.",
    createdAt: h(3),
  },
  {
    id: "m2",
    threadId: "t1",
    authorId: YOU_ID,
    body: "Perfect. I'll bring two jars and a bag of tea as a trade.",
    createdAt: h(2.7),
  },
  {
    id: "m3",
    threadId: "t1",
    authorId: "maya",
    body: "Tea is always welcome. See you by the lime tree.",
    createdAt: h(2.5),
  },
  {
    id: "m4",
    threadId: "t2",
    authorId: "jordan",
    body: "If you still need that saw, I can leave it with Nina — she's on your block.",
    createdAt: h(1.1),
  },
  {
    id: "m5",
    threadId: "t2",
    authorId: YOU_ID,
    body: "Omar posted it, but I'll let him know. Thank you — that's exactly the radius that works.",
    createdAt: h(1),
  },
  {
    id: "m6",
    threadId: "t3",
    authorId: "diego",
    body: "Lake loop Tuesday 8:15? I'll bring the slow Spanish and you can quiz me on chisel names.",
    createdAt: h(21),
  },
];

export const notifications: Notif[] = [
  {
    id: "n1",
    title: "Skill match nearby",
    body: "Omar needs a circular saw — your woodworking skill is a fit.",
    createdAt: h(2),
    read: false,
    screen: { name: "post", id: "p1" },
  },
  {
    id: "n2",
    title: "Diego replied",
    body: "Lake walk Tuesday? I need the steps anyway.",
    createdAt: h(22),
    read: false,
    screen: { name: "post", id: "p13" },
  },
  {
    id: "n3",
    title: "Hike is tomorrow-ish",
    body: "Temescal Canyon ridge — you RSVP'd. Leah posted a reminder in Trail Club.",
    createdAt: h(6),
    read: false,
    screen: { name: "post", id: "p3" },
  },
  {
    id: "n4",
    title: "New in Eastside Growers",
    body: "Maya offered kombucha SCOBYs in Silver Lake.",
    createdAt: h(5),
    read: true,
    screen: { name: "post", id: "p2" },
  },
];
